### ISSUE TITLE
Is it possible to add "current_temperature" to an external temperature sensor?

### ISSUE THREAD

**Issue by goxofy** [mullerdavid/hass_GreeExt#1]
Hi, @mullerdavid !

I have a problem with the "current_temperature" of my AC, my Gree A/C doesn't support  "current_temperature"  property and shows a wrong value of "-35", so is it possile to add a feature in this GreeExt that I could set the value of  "current_temperature" from an external temperature sensor?

Thanks!

**Comment by mullerdavid** [comment]
Hi, i'm sitting on top of the builtin gree integration, thus only controlling features that I can access. 

You might want to try this other integration, i think they might have what you need.
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent

**Comment by goxofy** [comment]
ok thanks a lot.
