### ISSUE TITLE
noob issue

### ISSUE THREAD

**Issue by alamoudimoh** [mullerdavid/hass_GreeExt#2]
Hi,

i am really noob, now i did the following:

1. install the integration thru HACS.
2. added the gree_ext: to my yaml file

nothing worked, i know i missed the copy part cuz i am not sure how to get it (or did i do something wrong)

BTW.... this is a good work u did

**Comment by mullerdavid** [comment]
I will give a more detailed example if I get back home after easter holiday.

**Comment by mullerdavid** [comment]
README should contain a basic example now.

**Comment by alamoudimoh** [comment]
thnx
